title: Fichier

columns:
  - width: 1/2
    sections:
      content:
        type: fields
        fields:
          markers:
            type: structure
            fields:
              text:
                label: Texte
                type: writer
          
  - width: 1/2
    sections:
      meta:
        type: fields
        fields:
          alt:
            label: Texte alternatif
            type: text
          caption:
            label: Légende
            type: markdown
          layout:
            type: select
            label: Mise en page
            default: one_of_one
            options:
              one_of_three: 1/3
              two_of_three: 2/3
              one_of_two: 1/2
              one_of_one: 1/1
